load("@lcm//lcm-bazel:lcm_cc_library_srcs.bzl", "lcm_cc_library_srcs")
load("@lcm//lcm-bazel:lcm_java_library_srcs.bzl", "lcm_java_library_srcs")
load("@lcm//lcm-bazel:lcm_library.bzl", "lcm_library")
load("@lcm//lcm-bazel:lcm_py_library_srcs.bzl", "lcm_py_library_srcs")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_python//python:py_library.bzl", "py_library")
load("@rules_java//java:java_library.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

LCM_SRCS = glob(["*.lcm"])

lcm_library(
    name = "messages",
    srcs = LCM_SRCS,
    lcm_package = "drake_jaco_driver",
)

lcm_cc_library_srcs(
    name = "messages_cc_srcs",
    src = ":messages",
)

lcm_py_library_srcs(
    name = "messages_py_srcs",
    src = ":messages",
)

lcm_java_library_srcs(
    name = "messages_java_srcs",
    src = ":messages",
)

cc_library(
    name = "lcmtypes_drake_jaco_driver_cc",
    srcs = [":messages_cc_srcs"],
    includes = ["."],
)

py_library(
    name = "lcmtypes_drake_jaco_driver_py",
    srcs = [":messages_py_srcs"],
    imports = ["."],
)

java_library(
    name = "lcmtypes_drake_jaco_driver_java",
    srcs = [":messages_java_srcs"],
    deps = ["@lcm//lcm-java"],
)
